name: React tests
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: node --version
      - run: yarn
      - run: yarn test:ci
